name = input("Enter a name: ")
adjective1 = input("Enter an adjective: ")
adjective2 = input("Enter an adjective: ")
adverb = input("Enter an adverb: ")
food1 = input("Enter a food: ")
food2 = input("Enter a food: ")
noun = input("Enter a noun: ")
place = input("Enter a place: ")
verb = input("Enter a verb: ")
print(name + " was planning a dream vacation to " + place + ". " + name + " was especially looking forward to trying the local cuisine, including " + adjective1 + " " + food1 + " and " + food2 + ". \n" + name + " will have to practice the language " + adverb + " to make it easier to " + verb + " with people. \n" + name + " has a long list of sights to see, including the " + noun + " museum and the " + adjective2 + " park.")
